name: Build Jar

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build mod jar
        run: ./gradlew build

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: skinwalker-jar
          path: build/libs/*.jar
